#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-cf"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "67b9f2d2ed3a4b689cc6692a77fe1cd3" }
]

[assets]
directory = "./public"
